### ISSUE TITLE
Remove volume control?

### ISSUE THREAD

**Issue by arkon** [J-Cotter/LISTEN.moe-Unofficial-Android-App#7]
A app-specific volume control seems odd since no other app does that, since the user would just use the system-wide media volume control. This is open to discussion though, since the website does have the feature.

**Comment by J-Cotter** [comment]
In my opinion giving the user finer control over the volume is very beneficial to their overall experience. 

Let's say a user has system media volume at 70%, a volume they enjoy watching videos at on youtube. The user is listening to the radio in the background with the in-app volume at 50%, but they decide to watch a youtube video, so the radio stops playing (once #4 has been fully implemented, also including other apps stopping the radio). In this scenario the user does not need to increase the system volume as it is already at 70%. Once the video ends and the radio resumes (again, pending implementation), the user does not have to decrease the volume as the radio is alredy set to 50% of the system volume.

If anything I am surprised more apps don't do this. I know changing the volume on a phone is incredibly easy to do but if you can save someone the effort, then why not...

I will leave this open if you have anything to add, if not it can be closed.

**Comment by arkon** [comment]
I suppose it's fine to have.
